set(ASSETS_US
    ${CMAKE_SOURCE_DIR}/assets/demos/bbh.bin
    ${CMAKE_SOURCE_DIR}/assets/demos/bitdw.bin
    ${CMAKE_SOURCE_DIR}/assets/demos/ccm.bin
    ${CMAKE_SOURCE_DIR}/assets/demos/hmc.bin
    ${CMAKE_SOURCE_DIR}/assets/demos/jrb.bin
    ${CMAKE_SOURCE_DIR}/assets/demos/pss.bin
    ${CMAKE_SOURCE_DIR}/assets/demos/unused.bin
    ${CMAKE_SOURCE_DIR}/assets/demos/wf.bin
    ${CMAKE_SOURCE_DIR}/levels/bbh/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitdw/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitdw/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitdw/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitdw/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitfs/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitfs/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitfs/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bits/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bits/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bits/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_1/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_1/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_1/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_2/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_3/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_3/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_3/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/5.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/10.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/11.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/12.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/13.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/14.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/15.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/16.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/17.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/18.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/19.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/2.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/20.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/21.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/22.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/23_us.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/24_us.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/25.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/26.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/27.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/28.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/29.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/30.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/31.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/32.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/33.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/34.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/35.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/36.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/37.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/38.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/39.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/40.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/9.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/castle_light.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/10.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/11.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/12.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/8.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/9.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ending/cake.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/intro/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/intro/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/intro/2_copyright.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/intro/3_tm.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/jrb/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/jrb/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/jrb/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/jrb/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/10.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/11.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/12.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/13.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/14.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/15.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/16.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/17.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/18.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/19.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/20.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/21.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/22.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/23.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/24.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/25.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/26.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/27.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/28.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/29.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/30.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/31.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/32.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/9.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.00018.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.00818.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.01018.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.02018.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.03468.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.03C68.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.04468.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.04C68.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.05468.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.06328.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.06B28.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.073D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.075D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.077D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.079D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.07BD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.07DD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.07FD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.081D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.083D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.085D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.087D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.089D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.08BD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.08DD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.08FD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.091D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.093D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.095D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.097D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.099D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.09BD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.09DD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.09FD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A1D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A3D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A5D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A7D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A9D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0D1A8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0E1A8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AC40.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AC80.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0ACC0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AD00.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AD40.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AD80.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0ADC0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AE00.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AE40.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AE80.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AEC0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AF00.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AF40.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AF80.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AFC0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B000.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B040.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B080.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B0C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B100.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B140.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B180.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B1C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B200.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B240.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B280.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B2C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B300.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B340.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B380.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B3C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B400.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B440.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B480.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B4C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B500.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B540.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B580.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B5C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B600.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B640.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B680.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B6C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B700.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B740.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B780.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B7C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B800.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/pss/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/pss/1.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/pss/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/rr/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/rr/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/rr/quarter_flying_carpet.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/1.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/10.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/11.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/9.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/thi/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/thi/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/totwc/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/totwc/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/totwc/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/totwc/3.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ttc/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttc/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttc/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/0.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/vcutm/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/vcutm/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/vcutm/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/vcutm/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/5.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/sound/samples/bowser_organ/00_organ_C3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/bowser_organ/01_organ_C4.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/bowser_organ/02_boys_choir_Bb4.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/course_start/00_la_E3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/00_banjo_D2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/01_banjo_A2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/02_violin_B2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/03_human_whistle_C3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/05_acoustic_bass_A1.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/06_kick_drum_1.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/07_rimshot.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/08.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/09.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/0A_tambourine.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/0B.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/0C_conga_stick.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/0D_clave.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/0E_hihat_closed.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/0F_hihat_open.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/10_cymbal_bell.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/11_splash_cymbal.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/12_snare_drum_1.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/13_snare_drum_2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/14_strings_Eb2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/15_strings_B3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/16_french_horns_C3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/18_timpani.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/19_brass_Eb3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/1B_percussive_synth_Eb3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/1C_les_paul_guitar_E2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/1D.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/1E_closed_triangle.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/1F_open_triangle.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/20_cabasa.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/21_sine_bass_Bb2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/22_boys_choir_Bb4.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/23_strings_Eb2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/26_crystal_rhodes_C4.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/27_harpsichord_F3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/28_sitar_1_A2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/29_orchestra_hit_C3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/2A_tabla_riff_1.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/2B_tabla_riff_2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/2C_tabla_riff_3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/2D_trombone_Bb2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/2E_accordion_C4.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/2F_sleigh_bells.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/30_rarefaction-lahna_E4.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/31_rarefaction-convolution_Eb2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/32_metal_rimshot.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/33_kick_drum_2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/34_alto_flute_A4.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/35_gospel_organ_F4.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/36_sawtooth_synth_Eb1.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/37_square_synth_C5.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/38_electric_kick_drum.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/3A_music_box_C5.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/3B_acoustic_guitar_A1.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/3C_acoustic_guitar_E3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/3D_acoustic_guitar_B6.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/3E_monk_choir_B2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/3F_small_gamelan.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/40_fu_yin_gong_C4.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/41_pan_flute_C3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/43_harmonica_C4.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/45_french_horns_C4.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/46_pizzicato_strings_Bb2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/instruments/47_pizzicato_strings_Bb3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/piranha_music_box/00_music_box_C5.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_1/00_twirl.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_1/01_brushing.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_1/02_hand_touch.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_1/03_yoshi.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_1/04_plop.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_1/05_heavy_landing.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_4/00.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_4/01.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_4/02.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_4/03.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_4/04.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_4/05.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_4/06.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_4/07.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_4/08.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_4/09.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/00.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/01.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/02.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/03.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/04.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/05.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/06.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/07.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/08.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/09.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/0A.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/0B.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/0C.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/0D.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/0E.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/0F.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/10.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/11.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/12.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/13.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/14.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/15.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/16.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/17.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/18.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/19.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/1A.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/1B.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_5/1C.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/00.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/01.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/02.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/03.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/04.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/05.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/06.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/07.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/08.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/09.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/0A.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/0B.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/0C.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_6/0D.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/00.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/01.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/02.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/03.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/04.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/05.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/06.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/07.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/08.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/09.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/0A.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/0B.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/0C.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_7/0D_chain_chomp_bark.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_9/00.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_9/01.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_9/02.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_9/03.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_9/04_camera_buzz.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_9/05_camera_shutter.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_9/06.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/00_mario_jump_hoo.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/01_mario_jump_wah.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/02_mario_yah.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/03_mario_haha.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/04_mario_yahoo.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/05_mario_uh.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/06_mario_hrmm.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/07_mario_wah2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/08_mario_whoa.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/09_mario_eeuh.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/0A_mario_attacked.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/0B_mario_ooof.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/0C_mario_here_we_go.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/0D_mario_yawning.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/0E_mario_snoring1.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/0F_mario_snoring2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/10_mario_doh.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/11_mario_game_over.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/12_mario_hello.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/13_mario_press_start_to_play.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/14_mario_twirl_bounce.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/15_mario_snoring3.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/16_mario_so_longa_bowser.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/17_mario_ima_tired.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/18_mario_waha.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/19_mario_yippee.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario/1A_mario_lets_a_go.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/00_mario_waaaooow.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/01_mario_hoohoo.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/02_mario_panting.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/03_mario_dying.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/04_mario_on_fire.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/05_mario_uh2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/06_mario_coughing.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/07_mario_its_a_me_mario.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/08_mario_punch_yah.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/09_mario_punch_hoo.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/0A_mario_mama_mia.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/0B_mario_okey_dokey.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/0C_mario_drowning.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/0D_mario_thank_you_playing_my_game.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/0E_peach_dear_mario.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/0F_peach_mario.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/10_peach_power_of_the_stars.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/11_peach_thanks_to_you.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/12_peach_thank_you_mario.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/13_peach_something_special.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/14_peach_bake_a_cake.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/15_peach_for_mario.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_mario_peach/16_peach_mario2.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_terrain/00_step_default.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_terrain/01_step_grass.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_terrain/02_step_stone.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_terrain/03_step_spooky.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_terrain/04_step_snow.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_terrain/05_step_ice.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_terrain/06_step_metal.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_terrain/07_step_sand.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_water/00_plunge.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_water/01_splash.aiff
    ${CMAKE_SOURCE_DIR}/sound/samples/sfx_water/02_swim.aiff
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/01_cutscene_collect_star.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/02_menu_title_screen.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/03_level_grass.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/04_level_inside_castle.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/05_level_water.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/06_level_hot.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/07_level_boss_koopa.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/08_level_snow.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/09_level_slide.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/0A_level_spooky.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/0B_event_piranha_plant.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/0C_level_underground.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/0D_menu_star_select.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/0E_event_powerup.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/0F_event_metal_cap.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/10_event_koopa_message.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/11_level_koopa_road.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/12_event_high_score.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/13_event_merry_go_round.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/14_event_race.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/15_cutscene_star_spawn.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/16_event_boss.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/17_cutscene_collect_key.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/18_event_endless_stairs.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/19_level_boss_koopa_final.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/1A_cutscene_credits.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/1B_event_solve_puzzle.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/1C_event_toad_message.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/1D_event_peach_message.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/1E_cutscene_intro.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/1F_cutscene_victory.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/20_cutscene_ending.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/21_menu_file_select.m64
    ${CMAKE_SOURCE_DIR}/sound/sequences/us/22_cutscene_lakitu.m64
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.09800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.0B800.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.0C000.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/bubble.06048.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/flower.00008.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/flower.00808.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/flower.01008.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/flower.01808.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.02020.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.02820.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.03020.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.03820.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.04020.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.04820.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.05020.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.05820.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/tiny_bubble.0684C.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/tiny_bubble.06AD8.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.09800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.0B000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.0B800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.09800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.0B000.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.09800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.0B000.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.0B800.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.0B000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.0B800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/hand_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/hand_open.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/mario_face_shine.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_2.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_3.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_4.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_5.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_6.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_7.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/sparkle_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/sparkle_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/sparkle_2.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/sparkle_3.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/sparkle_4.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/sparkle_5.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_2.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_3.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_4.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_5.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_6.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_7.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_00.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_01.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_02.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_03.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_04.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_05.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_06.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_07.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_08.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_09.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_10.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_11.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_12.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_13.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_14.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_15.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_16.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_17.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_18.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_19.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_20.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_21.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_22.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_23.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_24.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_25.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_26.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_27.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_28.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_29.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_30.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_31.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_32.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_33.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_34.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_35.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_36.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_37.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_38.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_39.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_40.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_41.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_42.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_43.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_44.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_45.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_46.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_47.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_48.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_49.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.08400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.09800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.0B000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.0B800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.0C000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.09800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.0B000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.0B400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.0BC00.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05900.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05940.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05980.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.059C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05A00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05A40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05A80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05AC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05B00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05B40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05B80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05BC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05C00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05C40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05C80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05CC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05D00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05D40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05D80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05DC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05E00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05E40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05E80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05EC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05F00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05F40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05F80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05FC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06000.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06040.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06080.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.060C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06100.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06140.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06180.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.061C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06200.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06240.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06280.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.062C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06300.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06340.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06380.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.063C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06400.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06410.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06420.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06440.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06480.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.064C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06500.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06540.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06580.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.065C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06600.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06640.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06680.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.066C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06700.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06740.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06780.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.067C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06800.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06840.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06880.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.068C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06900.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06940.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06980.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.069C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06A00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06A40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06A80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06AC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06B00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06B40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06B80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06BC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06C00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06C40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06C80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06CC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06D00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06D40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06D80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06DC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06E00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06E40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06E80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06EC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06F00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06F40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06F80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06FC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00200.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00600.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00C00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00E00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01200.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01600.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01C00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01E00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02200.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02C00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02E00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.03200.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.03600.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.03A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.03C00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.04400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.04A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.05600.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.05A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.05C00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06200.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06280.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06300.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06380.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06480.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06500.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06580.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06600.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06680.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06700.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06780.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06880.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06900.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06980.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06A80.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06B00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06B80.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06C00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06C80.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06D00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06D80.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06E00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06E80.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06F00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06F80.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.07080.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.07340.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.07B50.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.07D50.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.07F50.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.08150.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.081D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.0F458.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.0FC58.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.10458.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.11458.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.11C58.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.12458.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.12C58.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.13458.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.13C58.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.14838.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/shadow_quarter_circle.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/shadow_quarter_square.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/sky/metal_hole.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/skyboxes/bbh.png
    ${CMAKE_SOURCE_DIR}/textures/skyboxes/bidw.png
    ${CMAKE_SOURCE_DIR}/textures/skyboxes/bitfs.png
    ${CMAKE_SOURCE_DIR}/textures/skyboxes/bits.png
    ${CMAKE_SOURCE_DIR}/textures/skyboxes/ccm.png
    ${CMAKE_SOURCE_DIR}/textures/skyboxes/cloud_floor.png
    ${CMAKE_SOURCE_DIR}/textures/skyboxes/clouds.png
    ${CMAKE_SOURCE_DIR}/textures/skyboxes/ssl.png
    ${CMAKE_SOURCE_DIR}/textures/skyboxes/water.png
    ${CMAKE_SOURCE_DIR}/textures/skyboxes/wdw.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.09000.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.09800.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.0A800.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.0B000.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.0B800.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.001C0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.00E40.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.01AC0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.02740.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.033C0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.04040.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.04CC0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.05940.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.0B800.rgba16.png
)
