set(LEVEL_PNGS_JP
    ${CMAKE_SOURCE_DIR}/levels/bbh/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitdw/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitdw/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitdw/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitdw/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitfs/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitfs/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitfs/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bits/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bits/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bits/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_1/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_1/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_1/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_2/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_3/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_3/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_3/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/10.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/11.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/12.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/13.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/14.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/15.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/16.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/17.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/18.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/19.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/2.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/20.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/21.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/22.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/23.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/24.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/25.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/26.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/27.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/28.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/29.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/30.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/31.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/32.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/33.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/34.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/35.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/36.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/37.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/38.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/39.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/40.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/9.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/castle_light.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/10.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/11.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/12.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/8.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/9.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/4.rgba16.png
    # cakes are processed in convert_cakes.cmake
    #${CMAKE_SOURCE_DIR}/levels/ending/cake.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/intro/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/intro/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/intro/2_copyright.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/intro/3_tm.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/jrb/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/jrb/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/jrb/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/jrb/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/10.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/11.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/12.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/13.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/14.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/15.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/16.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/17.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/18.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/19.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/20.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/21.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/22.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/23.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/24.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/25.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/26.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/27.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/28.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/29.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/30.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/31.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/32.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/9.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.00018.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.00818.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.01018.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.02018.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.03468.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.03C68.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.04468.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.04C68.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.05468.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.06328.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.06B28.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.073D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.075D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.077D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.079D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.07BD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.07DD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.07FD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.081D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.083D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.085D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.087D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.089D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.08BD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.08DD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.08FD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.091D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.093D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.095D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.097D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.099D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.09BD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.09DD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.09FD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A1D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A3D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A5D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A7D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A9D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0AC48.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0AC88.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0ACC8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0AD08.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0AD48.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0AD88.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0ADC8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0AE08.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0AE48.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0AE88.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0AEC8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0AF08.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0AF48.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0AF88.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0AFC8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B008.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B048.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B088.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B0C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B108.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B148.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B188.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B1C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B208.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B248.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B288.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B2C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B308.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B348.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B388.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B3C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B408.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B448.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B488.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B4C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B508.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B548.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B588.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B5C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B608.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B648.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B688.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B6C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B708.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B748.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B788.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B7C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B808.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B848.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B888.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B8C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B908.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B948.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B988.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0B9C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BA08.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BA48.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BA88.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BAC8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BB08.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BB48.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BB88.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BBC8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BC08.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BC48.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BC88.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BCC8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BD08.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BD48.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BD88.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BDC8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BE08.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BE48.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BE88.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BEC8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BF08.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BF48.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BF88.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0BFC8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C008.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C048.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C088.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C0C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C108.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C148.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C188.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C1C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C208.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C248.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C288.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C2C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C308.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C348.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C388.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C3C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C408.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C448.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C488.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C4C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C508.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C548.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C588.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C5C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C608.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C648.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C688.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C6C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C708.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C748.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C788.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C7C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C808.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C848.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C888.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C8C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C908.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C948.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C988.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0C9C8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0CA08.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0CA48.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0CA88.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0CAC8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0CB08.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0CB48.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0CB88.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0CBC8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0CC08.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0CC48.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0CC88.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0CCC8.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0D1A8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0E1A8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/pss/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/pss/1.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/pss/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/rr/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/rr/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/rr/quarter_flying_carpet.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/1.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/10.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/11.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/9.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/thi/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/thi/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/totwc/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/totwc/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/totwc/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/totwc/3.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ttc/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttc/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttc/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/0.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/vcutm/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/vcutm/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/vcutm/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/vcutm/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/5.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/4.rgba16.png
)
set(LEVEL_PNGS ${LEVEL_PNGS_JP})
