set(LEVEL_PNGS_US
    ${CMAKE_SOURCE_DIR}/levels/bbh/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bbh/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitdw/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitdw/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitdw/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitdw/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitfs/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitfs/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bitfs/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bits/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bits/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bits/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bob/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_1/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_1/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_1/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_2/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_3/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_3/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/bowser_3/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_grounds/5.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/10.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/11.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/12.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/13.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/14.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/15.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/16.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/17.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/18.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/19.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/2.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/20.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/21.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/22.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/23_us.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/24_us.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/25.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/26.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/27.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/28.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/29.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/30.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/31.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/32.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/33.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/34.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/35.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/36.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/37.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/38.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/39.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/40.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/9.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/castle_inside/castle_light.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/10.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/11.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/12.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/8.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ccm/9.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/cotmc/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ddd/4.rgba16.png
    # cakes are processed in convert_cakes.cmake
    #${CMAKE_SOURCE_DIR}/levels/ending/cake.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/hmc/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/intro/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/intro/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/intro/2_copyright.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/intro/3_tm.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/jrb/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/jrb/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/jrb/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/jrb/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/10.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/11.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/12.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/13.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/14.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/15.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/16.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/17.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/18.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/19.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/20.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/21.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/22.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/23.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/24.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/25.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/26.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/27.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/28.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/29.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/30.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/31.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/32.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/lll/9.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.00018.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.00818.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.01018.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.02018.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.03468.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.03C68.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.04468.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.04C68.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.05468.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.06328.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.06B28.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.073D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.075D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.077D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.079D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.07BD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.07DD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.07FD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.081D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.083D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.085D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.087D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.089D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.08BD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.08DD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.08FD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.091D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.093D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.095D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.097D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.099D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.09BD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.09DD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.09FD0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A1D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A3D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A5D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A7D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0A9D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0D1A8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7.0E1A8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AC40.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AC80.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0ACC0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AD00.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AD40.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AD80.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0ADC0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AE00.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AE40.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AE80.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AEC0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AF00.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AF40.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AF80.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0AFC0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B000.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B040.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B080.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B0C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B100.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B140.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B180.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B1C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B200.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B240.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B280.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B2C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B300.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B340.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B380.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B3C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B400.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B440.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B480.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B4C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B500.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B540.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B580.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B5C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B600.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B640.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B680.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B6C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B700.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B740.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B780.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B7C0.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/menu/main_menu_seg7_us.0B800.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/pss/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/pss/1.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/pss/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/rr/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/rr/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/rr/quarter_flying_carpet.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/sl/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/1.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/10.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/11.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ssl/9.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/thi/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/thi/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/totwc/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/totwc/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/totwc/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/totwc/3.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ttc/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttc/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttc/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/0.ia16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/5.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/6.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/7.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/ttm/8.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/vcutm/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/vcutm/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/vcutm/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/vcutm/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wdw/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/4.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wf/5.ia8.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/0.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/1.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/2.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/3.rgba16.png
    ${CMAKE_SOURCE_DIR}/levels/wmotr/4.rgba16.png
)
set(LEVEL_PNGS ${LEVEL_PNGS_US})
