set(TEXTURE_PNGS_US
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.09800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.0B800.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/cave/hmc_textures.0C000.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/bubble.06048.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/flower.00008.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/flower.00808.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/flower.01008.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/flower.01808.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.02020.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.02820.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.03020.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.03820.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.04020.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.04820.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.05020.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/lava_bubble.05820.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/tiny_bubble.0684C.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/effect/tiny_bubble.06AD8.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.09800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.0B000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/fire/lll_textures.0B800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.09800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/generic/bob_textures.0B000.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.09800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.0B000.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/grass/wf_textures.0B800.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.0B000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/inside/inside_castle_textures.0B800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/hand_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/hand_open.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/mario_face_shine.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_2.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_3.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_4.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_5.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_6.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/red_star_7.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/sparkle_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/sparkle_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/sparkle_2.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/sparkle_3.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/sparkle_4.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/sparkle_5.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_2.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_3.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_4.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_5.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_6.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/intro_raw/white_star_7.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_00.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_01.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_02.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_03.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_04.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_05.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_06.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_07.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_08.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_09.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_10.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_11.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_12.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_13.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_14.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_15.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_16.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_17.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_18.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_19.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_20.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_21.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_22.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_23.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_24.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_25.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_26.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_27.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_28.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_29.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_30.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_31.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_32.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_33.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_34.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_35.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_36.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_37.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_38.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_39.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_40.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_41.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_42.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_43.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_44.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_45.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_46.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_47.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_48.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/ipl3_raw/ipl3_font_49.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/machine/ttc_textures.08400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.09800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.0B000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.0B800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/mountain/ttm_textures.0C000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.09800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.0B000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.0B400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/outside/castle_grounds_textures.0BC00.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05900.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05940.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05980.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.059C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05A00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05A40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05A80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05AC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05B00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05B40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05B80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05BC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05C00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05C40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05C80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05CC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05D00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05D40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05D80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05DC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05E00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05E40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05E80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05EC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05F00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05F40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05F80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.05FC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06000.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06040.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06080.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.060C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06100.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06140.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06180.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.061C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06200.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06240.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06280.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.062C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06300.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06340.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06380.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.063C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06400.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06410.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06420.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06440.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06480.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.064C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06500.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06540.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06580.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.065C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06600.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06640.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06680.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.066C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06700.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06740.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06780.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.067C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06800.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06840.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06880.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.068C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06900.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06940.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06980.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.069C0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06A00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06A40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06A80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06AC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06B00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06B40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06B80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06BC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06C00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06C40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06C80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06CC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06D00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06D40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06D80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06DC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06E00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06E40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06E80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06EC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06F00.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06F40.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06F80.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/font_graphics.06FC0.ia4.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00200.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00600.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00C00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.00E00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01200.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01600.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01C00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.01E00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02200.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02C00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.02E00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.03200.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.03600.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.03A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.03C00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.04400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.04A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.05600.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.05A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.05C00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06200.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06280.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06300.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06380.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06400.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06480.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06500.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06580.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06600.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06680.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06700.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06780.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06880.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06900.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06980.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06A00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06A80.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06B00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06B80.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06C00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06C80.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06D00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06D80.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06E00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06E80.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06F00.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.06F80.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.07080.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.07340.ia1.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.07B50.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.07D50.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.07F50.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.08150.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.081D0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.0F458.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.0FC58.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.10458.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.11458.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.11C58.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.12458.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.12C58.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.13458.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.13C58.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/segment2.14838.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/shadow_quarter_circle.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/segment2/shadow_quarter_square.ia8.png
    ${CMAKE_SOURCE_DIR}/textures/sky/metal_hole.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/sky/rr_textures.08000.rgba16.png
    # skyboxes are processed in convert_skyboxes.cmake
    #${CMAKE_SOURCE_DIR}/textures/skyboxes/bbh.png
    #${CMAKE_SOURCE_DIR}/textures/skyboxes/bidw.png
    #${CMAKE_SOURCE_DIR}/textures/skyboxes/bitfs.png
    #${CMAKE_SOURCE_DIR}/textures/skyboxes/bits.png
    #${CMAKE_SOURCE_DIR}/textures/skyboxes/ccm.png
    #${CMAKE_SOURCE_DIR}/textures/skyboxes/cloud_floor.png
    #${CMAKE_SOURCE_DIR}/textures/skyboxes/clouds.png
    #${CMAKE_SOURCE_DIR}/textures/skyboxes/ssl.png
    #${CMAKE_SOURCE_DIR}/textures/skyboxes/water.png
    #${CMAKE_SOURCE_DIR}/textures/skyboxes/wdw.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.01000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.02000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.03000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.04000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.09000.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/snow/ccm_textures.09800.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.05000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.07000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.08000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.0A800.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.0B000.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/spooky/bbh_textures.0B800.ia16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.001C0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.00E40.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.01AC0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.02740.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.033C0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.04040.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.04CC0.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/title_screen_bg/title_screen_bg.05940.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.00000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.00800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.01800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.02800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.03800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.04800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.05800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.06000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.06800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.07800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.08800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.09000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.0A000.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.0A800.rgba16.png
    ${CMAKE_SOURCE_DIR}/textures/water/jrb_textures.0B800.rgba16.png
)
set(TEXTURE_PNGS ${TEXTURE_PNGS_US})
