set(ACTOR_PNGS_JP
    ${CMAKE_SOURCE_DIR}/actors/amp/amp_body.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/amp/amp_electricity.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/amp/amp_eyes.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/amp/amp_mouth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/blue_coin_switch/blue_coin_switch_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/blue_coin_switch/blue_coin_switch_top.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/blue_fish/blue_fish.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bobomb/bob-omb_buddy_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bobomb/bob-omb_buddy_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bobomb/bob-omb_eyes.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bobomb/bob-omb_eyes_blink.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bobomb/bob-omb_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bobomb/bob-omb_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bomb/bomb_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bomb/bomb_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bomb/bomb_spike.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/boo/boo_eyes.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/boo/boo_mouth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/book/book_cover.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bookend/bookend_cover.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bookend/bookend_mouth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bookend/bookend_pages.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bookend/bookend_spine.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bookend/bookend_tooth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/boo_castle/bbh_boo_eyes.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/boo_castle/bbh_boo_mouth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_armband.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_armband_spike.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_blue_eye_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_body.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_chest.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_claw_edge.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_claw_horn_angle.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_claw_horn_tooth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_eyebrow.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_eye_center_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_eye_center_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_eye_closed_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_eye_closed_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_eye_far_left_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_eye_far_left_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_eye_half_closed_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_eye_half_closed_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_eye_left_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_eye_left_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_eye_right_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_eye_right_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_hair.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_mouth_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_muzzle.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_nostrils.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_shell.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_shell_edge.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_tongue.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser/bowser_upper_face.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_10.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_11.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_12.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_13.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_2.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_3.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_4.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_5.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_6.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_7.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_8.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bowser_flame/bowser_flame_9.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/breakable_box/cork_box_surface.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/breakable_box/crazy_box_surface.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bub/bub_eyes.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bub/bub_eye_border.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bub/bub_fins.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bub/bub_scales.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bubba/bubba_eyes_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bubba/bubba_eye_border.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bubba/bubba_fins.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bubba/bubba_scales.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bubba/bubba_sunglasses.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bubble/bubble.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bubble/mr_i_bubble.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bullet_bill/bullet_bill_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bullet_bill/bullet_bill_mouth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bully/bully_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bully/bully_horn.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bully/bully_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/bully/bully_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/burn_smoke/burn_smoke.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/butterfly/butterfly_wing.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/cannon_barrel/cannon_barrel.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/cannon_base/cannon_base.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/cannon_lid/cannon_lid.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/capswitch/cap_switch_base.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/capswitch/cap_switch_head.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/chain_ball/chain_ball.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chain_chomp/chain_chomp_bright_shine.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chain_chomp/chain_chomp_dull_shine.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chain_chomp/chain_chomp_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chain_chomp/chain_chomp_tongue.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chain_chomp/chain_chomp_tooth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chair/chair_bottom.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chair/chair_front.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chair/chair_leg.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chair/chair_surface_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/checkerboard_platform/checkerboard_platform.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/checkerboard_platform/checkerboard_platform_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chillychief/chill_bully_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chillychief/chill_bully_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chillychief/chill_bully_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chuckya/chuckya_body_arm_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chuckya/chuckya_body_arm_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chuckya/chuckya_eyes.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/chuckya/chuckya_hand_antenna.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/clam_shell/clam_shell.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/clam_shell/clam_shell_mouth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/coin/coin_front.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/coin/coin_side.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/coin/coin_tilt_left.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/coin/coin_tilt_right.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/cyan_fish/cyan_fish.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/dirt/dirt_particle.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/bbh_door.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/bbh_door_overlay.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/door_lock.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/hmc_mural_door.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/hmc_mural_door_overlay.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/metal_door.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/metal_door_overlay.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/one_star_door_sign.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/polished_wooden_door.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/polished_wooden_door_overlay.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/rough_wooden_door.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/rough_wooden_door_overlay.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/three_star_door_sign.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/door/zero_star_door_sign.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/dorrie/dorrie_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/dorrie/dorrie_skin.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/dorrie/dorrie_tongue.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/exclamation_box/exclamation_box_front.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/exclamation_box/exclamation_box_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/exclamation_box/metal_cap_box_front.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/exclamation_box/metal_cap_box_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/exclamation_box/vanish_cap_box_front.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/exclamation_box/vanish_cap_box_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/exclamation_box/wing_cap_box_front.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/exclamation_box/wing_cap_box_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/exclamation_box_outline/exclamation_box_outline.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/exclamation_box_outline/exclamation_point.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/explosion/explosion_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/explosion/explosion_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/explosion/explosion_2.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/explosion/explosion_3.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/explosion/explosion_4.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/explosion/explosion_5.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/explosion/explosion_6.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/eyerok/eyerok_bricks.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/eyerok/eyerok_eye_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/eyerok/eyerok_eye_mostly_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/eyerok/eyerok_eye_mostly_open.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/eyerok/eyerok_eye_open.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/flame/flame_0.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/flame/flame_1.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/flame/flame_2.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/flame/flame_3.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/flame/flame_4.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/flame/flame_5.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/flame/flame_6.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/flame/flame_7.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/flyguy/flyguy_cloth_wrinkle.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/flyguy/flyguy_face.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/flyguy/flyguy_propeller.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/fwoosh/fwoosh_face.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/goomba/goomba_body.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/goomba/goomba_face.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/goomba/goomba_face_blink.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/haunted_cage/bbh_cage_bars.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/haunted_cage/bbh_cage_double_ornament.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/haunted_cage/bbh_cage_floor.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/haunted_cage/bbh_cage_garbage.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/haunted_cage/bbh_cage_ornament.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/haunted_cage/bbh_cage_wooden_base.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/heart/spinning_heart.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/heave_ho/heave-ho_arm_ornament.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/heave_ho/heave-ho_face.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/heave_ho/heave-ho_logo.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/heave_ho/heave-ho_platform.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/heave_ho/heave-ho_roller.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/heave_ho/heave-ho_turnkey.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/hoot/hoot_eyes.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/hoot/hoot_wing.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/hoot/hoot_wing_tip.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/impact_ring/impact_ring_left_side.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/impact_ring/impact_ring_right_side.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/impact_smoke/impact_smoke_0.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/impact_smoke/impact_smoke_1.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/impact_smoke/impact_smoke_2.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/impact_smoke/impact_smoke_3.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/king_bobomb/bob-omb_buddy_body_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/king_bobomb/bob-omb_buddy_left_side_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/king_bobomb/bob-omb_buddy_right_side_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/king_bobomb/king_bob-omb_arm.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/king_bobomb/king_bob-omb_body_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/king_bobomb/king_bob-omb_crown_rim.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/king_bobomb/king_bob-omb_eyes.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/king_bobomb/king_bob-omb_eyes_blink.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/king_bobomb/king_bob-omb_hand.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/king_bobomb/king_bob-omb_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/king_bobomb/king_bob-omb_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/klepto/klepto_beak.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/klepto/klepto_chest_tuft.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/klepto/klepto_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/klepto/klepto_wing.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/klepto/klepto_wing_flap.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/koopa/koopa_eyes_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/koopa/koopa_eyes_open.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/koopa/koopa_eye_border.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/koopa/koopa_nostrils.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/koopa/koopa_shell_back.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/koopa/koopa_shell_front.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/koopa/koopa_shell_front_top.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/koopa/koopa_shoe.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/koopa_flag/koopa_flag_banner.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/koopa_shell/koopa_shell_back.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/koopa_shell/koopa_shell_front.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/lakitu_cameraman/lakitu_cameraman_cloud_face_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/lakitu_cameraman/lakitu_cameraman_eyes_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/lakitu_cameraman/lakitu_cameraman_eyes_open.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/lakitu_cameraman/lakitu_cameraman_frown.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/lakitu_cameraman/lakitu_cameraman_shell.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/lakitu_cameraman/lakitu_camera_lens.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/lakitu_enemy/lakitu_enemy_cloud_face_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/lakitu_enemy/lakitu_enemy_eyes_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/lakitu_enemy/lakitu_enemy_eyes_open.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/lakitu_enemy/lakitu_enemy_frown.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/lakitu_enemy/lakitu_enemy_shell.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/leaves/leaf.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mad_piano/mad_piano_body.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mad_piano/mad_piano_keys.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mad_piano/mad_piano_keys_corner.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mad_piano/mad_piano_keys_edge.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mad_piano/mad_piano_mouth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mad_piano/mad_piano_tooth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/manta/manta_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/manta/manta_fin_corner.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/manta/manta_fin_edge.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/manta/manta_gills.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_eyes_center.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_eyes_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_eyes_closed_unused_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_eyes_closed_unused_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_eyes_dead.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_eyes_down_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_eyes_half_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_eyes_left_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_eyes_right_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_eyes_up_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_logo.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_metal.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_metal_wing_tip_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_metal_wing_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_mustache.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_overalls_button.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_sideburn.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_wing.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario/mario_wing_tip.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario_cap/mario_cap_logo.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario_cap/mario_cap_metal.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario_cap/mario_cap_metal_wing_tip_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario_cap/mario_cap_metal_wing_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario_cap/mario_cap_wing.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mario_cap/mario_cap_wing_tip.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/metal_box/metal_box_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mips/mips_eyes.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mist/mist.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/moneybag/moneybag_eyes.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/moneybag/moneybag_mouth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/monty_mole/monty_mole_cheek.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/monty_mole/monty_mole_claw.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/monty_mole/monty_mole_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/monty_mole/monty_mole_nose.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/monty_mole/monty_mole_tooth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/monty_mole_hole/monty_mole_hole.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/mr_i_eyeball/mr_i_eyeball_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mr_i_eyeball/mr_i_eyeball_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mr_i_iris/mr_i_iris_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mr_i_iris/mr_i_iris_mostly_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mr_i_iris/mr_i_iris_mostly_open.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mr_i_iris/mr_i_iris_open.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/mushroom_1up/1-up_mushroom.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/peach/peach_chest_jewel.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/peach/peach_crown_jewel.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/peach/peach_dress.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/peach/peach_eye_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/peach/peach_eye_mostly_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/peach/peach_eye_mostly_open.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/peach/peach_eye_open.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/peach/peach_lips.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/peach/peach_lips_scrunched.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/peach/peach_nostril.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/pebble/pebble.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/penguin/penguin_beak.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/penguin/penguin_eye_angry.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/penguin/penguin_eye_angry_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/penguin/penguin_eye_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/penguin/penguin_eye_half_closed.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/penguin/penguin_eye_open.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/piranha_plant/piranha_plant_bottom_lip.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/piranha_plant/piranha_plant_leaf.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/piranha_plant/piranha_plant_skin.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/piranha_plant/piranha_plant_stem.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/piranha_plant/piranha_plant_tongue.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/piranha_plant/piranha_plant_tooth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/pokey/pokey_body.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/pokey/pokey_face.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/pokey/pokey_face_blink.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/poundable_pole/poundable_pole_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/poundable_pole/poundable_pole_top.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/power_meter/power_meter_five_segments.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/power_meter/power_meter_four_segments.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/power_meter/power_meter_full.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/power_meter/power_meter_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/power_meter/power_meter_one_segment.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/power_meter/power_meter_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/power_meter/power_meter_seven_segments.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/power_meter/power_meter_six_segments.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/power_meter/power_meter_three_segments.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/power_meter/power_meter_two_segments.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/purple_switch/purple_switch_base.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/purple_switch/purple_switch_exclamation_point.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/sand/sand_particle.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/scuttlebug/scuttlebug_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/scuttlebug/scuttlebug_iris.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/scuttlebug/scuttlebug_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/scuttlebug/scuttlebug_leg.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/scuttlebug/scuttlebug_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/seaweed/seaweed_base.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/seaweed/seaweed_lower_center.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/seaweed/seaweed_tip.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/seaweed/seaweed_upper_center.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/skeeter/skeeter_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/skeeter/skeeter_iris.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/smoke/smoke.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/snowman/mr_blizzard_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/snowman/mr_blizzard_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/snowman/mr_blizzard_mitten.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/snowman/mr_blizzard_mouth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/snowman/mr_blizzard_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/snufit/snufit_body.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/snufit/snufit_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/snufit/snufit_mask_strap.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/snufit/snufit_mouth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/sparkle/sparkle_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/sparkle/sparkle_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/sparkle/sparkle_2.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/sparkle/sparkle_3.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/sparkle/sparkle_4.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/sparkle/sparkle_5.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/sparkle_animation/sparkle_animation_0.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/sparkle_animation/sparkle_animation_1.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/sparkle_animation/sparkle_animation_2.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/sparkle_animation/sparkle_animation_3.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/sparkle_animation/sparkle_animation_4.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/spindrift/spindrift_face.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/spindrift/spindrift_head.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/spindrift/spindrift_leaf.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/spindrift/spindrift_petal.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/springboard/springboard_base_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/springboard/springboard_top_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/star/star_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/star/star_surface.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/stomp_smoke/stomp_smoke_0.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/stomp_smoke/stomp_smoke_1.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/stomp_smoke/stomp_smoke_2.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/stomp_smoke/stomp_smoke_3.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/stomp_smoke/stomp_smoke_4.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/stomp_smoke/stomp_smoke_5.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/sushi/sushi_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/sushi/sushi_snout.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/sushi/sushi_tooth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/swoop/swoop_body.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/swoop/swoop_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/swoop/swoop_nose.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/swoop/swoop_wing.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/thwomp/thwomp_face.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/thwomp/thwomp_surface.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/toad/toad_face.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/toad/toad_head.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/tornado/tornado.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/treasure_chest/treasure_chest_front.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/treasure_chest/treasure_chest_lock.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/treasure_chest/treasure_chest_lock_top.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/treasure_chest/treasure_chest_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/tree/palm_tree.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/tree/pine_tree.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/tree/snowy_pine_tree.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/tree/tree_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/tree/tree_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/ukiki/ukiki_butt.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/ukiki/ukiki_face.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/ukiki/ukiki_face_blink.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/ukiki/ukiki_fur.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/unagi/unagi_body.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/unagi/unagi_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/unagi/unagi_head_base.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/unagi/unagi_mouth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/unagi/unagi_tail.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/unagi/unagi_tooth.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/walk_smoke/walk_smoke_0.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/walk_smoke/walk_smoke_1.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/walk_smoke/walk_smoke_2.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/walk_smoke/walk_smoke_3.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/walk_smoke/walk_smoke_4.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/walk_smoke/walk_smoke_5.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/walk_smoke/walk_smoke_6.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/warp_pipe/warp_pipe_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/warp_pipe/warp_pipe_top.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_bubble/water_bubble.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_mine/water_mine_left_side_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_mine/water_mine_right_side_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_mine/water_mine_spike_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_ring/water_ring.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_splash/water_splash_0.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_splash/water_splash_1.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_splash/water_splash_2.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_splash/water_splash_3.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_splash/water_splash_4.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_splash/water_splash_5.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_splash/water_splash_6.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_splash/water_splash_7.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/water_wave/water_wave_0.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/water_wave/water_wave_1.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/water_wave/water_wave_2.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/water_wave/water_wave_3.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/whirlpool/whirlpool.ia16.png
    ${CMAKE_SOURCE_DIR}/actors/white_particle/snow_particle.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/white_particle_small/small_snow_particle.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/whomp/whomp_back.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/whomp/whomp_face.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/whomp/whomp_hand.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/whomp/whomp_surface.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/wiggler/wiggler_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/wiggler/wiggler_flower.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/wiggler/wiggler_frown.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/wiggler/wiggler_nose_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/wiggler/wiggler_nose_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/wiggler/wiggler_segment_left_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/wiggler/wiggler_segment_right_side.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/wooden_signpost/wooden_signpost_back.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/wooden_signpost/wooden_signpost_front.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/yellow_sphere/yellow_sphere.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/yellow_sphere_small/small_yellow_sphere.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/yoshi/yoshi_eye.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/yoshi/yoshi_eye_blink.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/yoshi/yoshi_nostril.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/yoshi_egg/yoshi_egg_0_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/yoshi_egg/yoshi_egg_1_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/yoshi_egg/yoshi_egg_2_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/yoshi_egg/yoshi_egg_3_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/yoshi_egg/yoshi_egg_4_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/yoshi_egg/yoshi_egg_5_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/yoshi_egg/yoshi_egg_6_unused.rgba16.png
    ${CMAKE_SOURCE_DIR}/actors/yoshi_egg/yoshi_egg_7_unused.rgba16.png
)
set(ACTORS_PNG_FILES ${ACTOR_PNGS_JP})